# Generated by Django 5.2.9 on 2025-12-13 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workitem_is_active_alter_workitem_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User')], db_index=True, max_length=50)),
                ('message', models.TextField(help_text='Message regarding status, review, or work clarification')),
                ('related_status', models.CharField(blank=True, help_text='Status this message refers to (optional)', max_length=30)),
                ('related_review', models.CharField(blank=True, help_text='Review decision this message refers to (optional)', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_item_messages', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.workitem')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender_role'], name='accounts_wo_sender__2b1a85_idx'), models.Index(fields=['created_at'], name='accounts_wo_created_b13a6b_idx')],
            },
        ),
    ]
