# Generated by Django 5.2.9 on 2025-12-27 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orgassignment',
            name='unique_user_org_path',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='accounts_te_team_ty_e2eb6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='accounts_te_parent__7bdc32_idx',
        ),
        migrations.AlterField(
            model_name='orgassignment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='team',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounts.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], db_index=True, default='user', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='orgassignment',
            constraint=models.UniqueConstraint(fields=('user',), name='one_org_assignment_per_user'),
        ),
    ]
