# Generated by Django 5.2.9 on 2025-12-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_orgassignment_unique_user_org_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this item was reviewed (approved or revised)', null=True),
        ),
        migrations.AlterField(
            model_name='workcycle',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive work cycles are hidden / archived manually'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when work was submitted', null=True),
        ),
    ]
