# Generated by Django 5.2.9 on 2026-01-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_workitem_reviewed_at_alter_workcycle_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitemmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this message has been read by the other party'),
        ),
        migrations.AddField(
            model_name='workitemmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the message was read', null=True),
        ),
        migrations.AddIndex(
            model_name='workitemmessage',
            index=models.Index(fields=['is_read'], name='accounts_wo_is_read_cdd92e_idx'),
        ),
        migrations.AddIndex(
            model_name='workitemmessage',
            index=models.Index(fields=['work_item', 'is_read'], name='accounts_wo_work_it_25e1b5_idx'),
        ),
    ]
