# Generated by Django 5.2.9 on 2026-01-02 12:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('reminder', 'Reminder'), ('status', 'Status'), ('review', 'Review'), ('assignment', 'Assignment'), ('message', 'Message'), ('system', 'System')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], db_index=True, default='info', max_length=20)),
                ('title', models.CharField(help_text='Short headline shown in notification list', max_length=200)),
                ('message', models.TextField(help_text='Detailed message shown when expanded')),
                ('action_url', models.CharField(blank=True, help_text='Optional URL the notification should link to', max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.workitem')),
                ('workcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.workcycle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['category'], name='notificatio_categor_fd561f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'), models.Index(fields=['recipient', 'category', 'is_read'], name='notificatio_recipie_130037_idx')],
            },
        ),
    ]
