# Generated by Django 5.2.9 on 2025-12-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDistributionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_workers', models.IntegerField(default=0)),
                ('approved_count', models.IntegerField(default=0)),
                ('needs_revision_count', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('in_progress_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('late_overdue_count', models.IntegerField(default=0)),
                ('approved_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionReviewQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision')], default='pending_review', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
