# Generated by Django 5.2.9 on 2025-12-10 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('submission_management', '0001_initial'),
        ('submission_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='statusdistributionmetrics',
            name='deadline_setting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_metrics', to='submission_settings.deadlinesubmissionsetting'),
        ),
        migrations.AddField(
            model_name='statusdistributionmetrics',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_metrics', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='submissionreviewqueue',
            name='department',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.AddField(
            model_name='submissionreviewqueue',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionreviewqueue',
            name='submission_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_queue_entry', to='submission_settings.submissionstatus'),
        ),
    ]
